export * from "./login.post";
export * from "./register.post";
export * from "./document_list.get";
export * from "./profile.get";
export * from "./document_upload.post";
export * from "./chat_suggestion.get";
export * from "./chat_history.get";
export * from "./send_chat.post";
export * from "./clear_chat.delete";
